### PR TITLE
Added Discord

### PR DESCRIPTION
**Pull request by adenosinetp10**
It isn't gaming without Discord.

### CODE REVIEW

**Comment by Schwarzeisc00l** [comment]
> It isn't gaming without Discord.

Yes

**Comment by adenosinetp10** [comment]
> > It isn't gaming without Discord.
> 
> Yes

What about accepting my pull request ?

**Review by Schwarzeisc00l — APPROVED** [review]

**Comment by Schwarzeisc00l** [comment]
> > > It isn't gaming without Discord.
> > 
> > 
> > Yes
> 
> What about accepting my pull request ?

Have i done it right? I don't know much about Github sorry.

**Comment by adenosinetp10** [comment]
> > > > It isn't gaming without Discord.
> > > 
> > > 
> > > Yes
> > 
> > 
> > What about accepting my pull request ?
> 
> Have i done it right? I don't know much about Github sorry.

You have to click the Merge Pull request Button before closing the pull request.
You can read more about it [here](https://zepel.io/blog/how-to-merge-branches-in-github/).
I was also like this when I was new to github, infact I still don't know much about git VCS and github too.

**Comment by Schwarzeisc00l** [comment]
> > > > > It isn't gaming without Discord.
> > > > 
> > > > 
> > > > Yes
> > > 
> > > 
> > > What about accepting my pull request ?
> > 
> > 
> > Have i done it right? I don't know much about Github sorry.
> 
> You have to click the Merge Pull request Button before closing the pull request.
> You can read more about it [here](https://zepel.io/blog/how-to-merge-branches-in-github/).
> I was also like this when I was new to github, infact I still don't know much about git VCS and github too.

lol ok

**Pull request closed without merging**
